// ---------------------------------------------------------------------------
// Sia blockchain explorer URL helpers
// ---------------------------------------------------------------------------
//
// The backend currently runs against the Zen testnet, so we default to the
// Zen Siascan explorer. To point at mainnet, set VITE_SIA_EXPLORER_URL to
// `https://siascan.com`.
//
// Verified routes (probed live against `https://zen.siascan.com/`):
//   - /block/<height | blockId>      -> dedicated block page
//   - /tx/<txId>                     -> dedicated transaction page
//   - /contract/<contractId>         -> dedicated contract page
//   - /host/<ed25519:hex pubkey>     -> dedicated host page
//   - /address/<sia address>         -> dedicated address page
//
// IMPORTANT: Sia object IDs are NOT on-chain entities — they are
// app-layer hashes generated by the indexer and never show up on the
// blockchain explorer. Do not link them to Siascan: it returns no
// results for them. Link hosts, contracts, txs, blocks, and addresses —
// those are real consensus-layer entities.

const DEFAULT_EXPLORER = 'https://zen.siascan.com';

const BASE = (
  (import.meta.env.VITE_SIA_EXPLORER_URL as string | undefined) ?? DEFAULT_EXPLORER
).replace(/\/$/, '');

/** The configured explorer base URL (no trailing slash). */
export const EXPLORER_BASE_URL = BASE;

/** Human-readable label for the configured explorer (for UI affordances). */
export const EXPLORER_LABEL = BASE.includes('zen.siascan.com')
  ? 'Zen Siascan'
  : BASE.includes('siascan.com')
    ? 'Siascan'
    : 'Sia Explorer';

/** True when we're pointing at the Zen testnet explorer. */
export const IS_TESTNET_EXPLORER = BASE.includes('zen.siascan.com');

function encode(value: string | number): string {
  return encodeURIComponent(String(value));
}

/**
 * URL builders for on-chain entities the Siascan explorer can resolve.
 * Intentionally omits `object(id)` — see the header comment above.
 */
export const explorerUrls = {
  /** Host public key, e.g. `ed25519:<64 hex chars>`. */
  host: (pubkey: string) => `${BASE}/host/${encode(pubkey)}`,

  /** File-contract ID (Hash256). */
  contract: (id: string) => `${BASE}/contract/${encode(id)}`,

  /** Transaction ID. */
  tx: (id: string) => `${BASE}/tx/${encode(id)}`,

  /** Block height (number) or block ID (hash). */
  block: (idOrHeight: string | number) => `${BASE}/block/${encode(idOrHeight)}`,

  /** Sia wallet address. */
  address: (addr: string) => `${BASE}/address/${encode(addr)}`,
};

/**
 * Props to spread onto an `<a>` pointing at the explorer. Always opens in a
 * new tab with safe `rel` values.
 */
export const EXTERNAL_LINK_PROPS = {
  target: '_blank' as const,
  rel: 'noopener noreferrer' as const,
};
